-- My Book Library database setup for Supabase
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  isbn text not null,
  title text not null,
  authors jsonb not null default '[]'::jsonb,
  description text not null default '',
  cover text not null default '',
  status text not null default 'read' check (status in ('read', 'reading', 'want')),
  added_at timestamptz not null default now(),
  constraint books_user_isbn_unique unique (user_id, isbn)
);

alter table public.books enable row level security;

drop policy if exists "Users can view their own books" on public.books;
create policy "Users can view their own books"
on public.books for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own books" on public.books;
create policy "Users can insert their own books"
on public.books for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own books" on public.books;
create policy "Users can update their own books"
on public.books for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own books" on public.books;
create policy "Users can delete their own books"
on public.books for delete
to authenticated
using (auth.uid() = user_id);

grant select, insert, update, delete on public.books to authenticated;
grant usage, select on sequence public.books_id_seq to authenticated;
